/*
 * Copyright 2026 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package com.linecorp.centraldogma.xds.internal;

import static com.linecorp.centraldogma.xds.internal.ControlPlaneService.ENDPOINTS_DIRECTORY;
import static com.linecorp.centraldogma.xds.internal.ControlPlaneService.K8S_ENDPOINTS_DIRECTORY;

import java.util.concurrent.CompletableFuture;
import java.util.function.Function;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;

import com.linecorp.armeria.common.util.Exceptions;
import com.linecorp.armeria.server.annotation.Get;
import com.linecorp.armeria.server.annotation.Param;
import com.linecorp.armeria.server.annotation.ProducesJson;
import com.linecorp.centraldogma.common.Entry;
import com.linecorp.centraldogma.common.EntryNotFoundException;
import com.linecorp.centraldogma.common.EntryType;
import com.linecorp.centraldogma.common.Revision;
import com.linecorp.centraldogma.server.storage.project.Project;
import com.linecorp.centraldogma.server.storage.repository.Repository;

/**
 * Serves read access to EDS (endpoint) resources of the xDS project without requiring a repository role.
 */
@ProducesJson
public final class XdsEndpointReadService {

    private final Project xdsProject;

    XdsEndpointReadService(Project xdsProject) {
        this.xdsProject = xdsProject;
    }

    /**
     * Lists the endpoint resources of the given {@code group}.
     */
    @Get("/xds/groups/{group}/endpoints")
    public CompletableFuture<JsonNode> listEndpoints(@Param String group) {
        final Repository repository = xdsProject.repos().get(group);
        return repository.find(Revision.HEAD, ENDPOINTS_DIRECTORY + "**," + K8S_ENDPOINTS_DIRECTORY + "**")
                         .thenApply(entries -> {
            final ArrayNode array = JsonNodeFactory.instance.arrayNode();
            for (Entry<?> entry : entries.values()) {
                if (entry.type() != EntryType.JSON && entry.type() != EntryType.YAML) {
                    continue;
                }
                final ObjectNode node = array.addObject();
                node.put("path", entry.path());
                node.put("type", entry.type().name());
                node.put("revision", entry.revision().major());
            }
            return array;
        });
    }

    /**
     * Returns the content of a single endpoint resource.
     */
    @Get("/xds/groups/{group}/endpoints/{*id}")
    public CompletableFuture<JsonNode> getEndpoint(@Param String group, @Param String id) {
        return readWithFallback(group, ENDPOINTS_DIRECTORY + id + ".yaml",
                                ENDPOINTS_DIRECTORY + id + ".json");
    }

    /**
     * Returns the content of a single endpoint generated by a Kubernetes aggregator (under
     * {@code /k8s/endpoints/}).
     */
    @Get("/xds/groups/{group}/k8s/endpoints/{*id}")
    public CompletableFuture<JsonNode> getK8sEndpoint(@Param String group, @Param String id) {
        return readWithFallback(group, K8S_ENDPOINTS_DIRECTORY + id + ".yaml",
                                K8S_ENDPOINTS_DIRECTORY + id + ".json");
    }

    private CompletableFuture<JsonNode> readWithFallback(String group, String yamlPath, String jsonPath) {
        final Repository repository = xdsProject.repos().get(group);
        return repository.get(Revision.HEAD, yamlPath)
                         .thenApply(XdsEndpointReadService::toNode)
                         .handle((result, cause) -> {
                             if (cause == null) {
                                 return CompletableFuture.completedFuture(result);
                             }
                             if (Exceptions.peel(cause) instanceof EntryNotFoundException) {
                                 return repository.get(Revision.HEAD, jsonPath)
                                                  .thenApply(XdsEndpointReadService::toNode);
                             }
                             final CompletableFuture<JsonNode> failed = new CompletableFuture<>();
                             failed.completeExceptionally(cause);
                             return failed;
                         })
                         .thenCompose(Function.identity());
    }

    private static JsonNode toNode(Entry<?> entry) {
        final ObjectNode node = JsonNodeFactory.instance.objectNode();
        node.put("path", entry.path());
        node.put("type", entry.type().name());
        node.put("revision", entry.revision().major());
        node.set("content", (JsonNode) entry.content());
        return node;
    }
}
