version: "{branch}.{build}"

init:
  - git config --global core.autocrlf true

build:
  verbosity: detailed

build_script:
  - gradlew.bat --no-daemon --stacktrace checkstyle test build

test: off

cache:
  - "%USERPROFILE%\\.gradle\\wrapper\\dists"
  - "%USERPROFILE%\\.gradle\\caches\\jars-3"
  - "%USERPROFILE%\\.gradle\\caches\\modules-2"
  - "%USERPROFILE%\\.gradle\\caches\\package-lists"
  - "%USERPROFILE%\\.gradle\\caches\\sphinx-binary"
  - "%USERPROFILE%\\.gradle\\go\\binary"

environment:
  JAVA_HOME: C:\Program Files\Java\jdk13
  GRADLE_OPTS: -Xmx1280m

matrix:
  fast_finish: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: uDUySAYLk8RjAL6ZAWd9K/hP9rV1/yYPz26CybZOPFaU2oHBlBbKIiPN9USkSRewVynqhxHqak8LhQ313/XQN2zusRnYhjMbmutCioAT4CY=
