/*
 * Copyright 2026 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
import { Button, Flex, HStack, Link, Spacer, Tag, Text, useDisclosure } from '@chakra-ui/react';
import { default as RouteLink } from 'next/link';
import { AiOutlineDelete } from 'react-icons/ai';
import { IoAddCircleOutline } from 'react-icons/io5';
import {
  ColumnDef,
  createColumnHelper,
  getCoreRowModel,
  getSortedRowModel,
  useReactTable,
} from '@tanstack/react-table';
import { useMemo, useState } from 'react';
import { DataTable } from 'dogma/features/xds/DataTable';
import { DeleteConfirmationModal } from 'dogma/common/components/DeleteConfirmationModal';
import { Deferred } from 'dogma/common/components/Deferred';
import { useDeleteResourceMutation, useListResourcesQuery } from 'dogma/features/xds/xdsApiSlice';
import { resourceName, XdsResourceDto, XdsResourceType, XDS_RESOURCE_META } from 'dogma/features/xds/XdsTypes';
import { useGroupWriteAccess } from 'dogma/common/useGroupWriteAccess';
import { useAppDispatch } from 'dogma/hooks';
import { newNotification } from 'dogma/features/notification/notificationSlice';
import ErrorMessageParser from 'dogma/features/services/ErrorMessageParser';

const columnHelper = createColumnHelper<XdsResourceDto>();

function resourceHref(group: string, type: XdsResourceType, params: Record<string, string>): string {
  const search = new URLSearchParams({ group, type, ...params });
  return `/app/xds/resource?${search.toString()}`;
}

export const ResourceList = ({ group, type }: { group: string; type: XdsResourceType }) => {
  const dispatch = useAppDispatch();
  const meta = XDS_RESOURCE_META[type];
  // Mutating controls (the Delete action column and the New button) are shown only to users with WRITE on the
  // group. Endpoints are listed even for users without access, so this also hides them there.
  const { hasWrite } = useGroupWriteAccess(group);
  const { data, isLoading, error } = useListResourcesQuery(
    { group, type },
    { refetchOnMountOrArgChange: true },
  );
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [target, setTarget] = useState('');
  const [deleteResource, { isLoading: isDeleting }] = useDeleteResourceMutation();

  const handleDelete = async () => {
    try {
      await deleteResource({ group, type, id: target }).unwrap();
      dispatch(newNotification(`${meta.label} deleted`, `${meta.label} '${target}' is deleted`, 'success'));
      onClose();
    } catch (err) {
      dispatch(newNotification(`Failed to delete the ${meta.label}`, ErrorMessageParser.parse(err), 'error'));
    }
  };

  const columns = useMemo(() => {
    const cols: ColumnDef<XdsResourceDto, string>[] = [
      columnHelper.accessor('id', {
        header: 'Name',
        // Shows the full xDS resource name; the link navigates by id. Resources generated by a k8s aggregator
        // (path under '/k8s/') carry a 'k8s' flag so the editor reads them from the k8s path and opens
        // read-only, and are marked with a 'Kubernetes' badge.
        cell: (info) => {
          const k8s = info.row.original.path.startsWith('/k8s/');
          const params = k8s ? { id: info.getValue(), k8s: 'true' } : { id: info.getValue() };
          return (
            <HStack spacing={2}>
              <Link as={RouteLink} href={resourceHref(group, type, params)} color="teal">
                {resourceName(group, info.row.original.path)}
              </Link>
              {k8s && (
                <Tag colorScheme="purple" size="sm">
                  Kubernetes
                </Tag>
              )}
            </HStack>
          );
        },
      }),
    ];
    // The Action column only holds the Delete button, so it is shown only to users who can write. k8s-generated
    // resources are managed by the aggregator and cannot be deleted here.
    if (hasWrite) {
      cols.push(
        columnHelper.accessor('id', {
          id: 'action',
          header: 'Action',
          enableSorting: false,
          cell: (info) =>
            info.row.original.path.startsWith('/k8s/') ? null : (
              <Button
                leftIcon={<AiOutlineDelete />}
                colorScheme="red"
                variant="ghost"
                size="sm"
                onClick={() => {
                  setTarget(info.getValue());
                  onOpen();
                }}
              >
                Delete
              </Button>
            ),
        }),
      );
    }
    return cols;
  }, [group, type, onOpen, hasWrite]);

  // Memoized so the table receives a stable data reference across re-renders (react-table requires this).
  const resources = useMemo(() => data || [], [data]);
  const table = useReactTable({
    data: resources,
    columns,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
  });

  return (
    <Deferred isLoading={isLoading} error={error}>
      {() => (
        <>
          {hasWrite && (
            <Flex>
              <Spacer />
              <Button
                as={RouteLink}
                href={resourceHref(group, type, { action: 'new' })}
                colorScheme="teal"
                size="sm"
                leftIcon={<IoAddCircleOutline />}
              >
                New {meta.label}
              </Button>
            </Flex>
          )}
          {resources.length === 0 ? (
            <Text mt={4} color="gray.500">
              No {meta.label.toLowerCase()}s in this group yet.
            </Text>
          ) : null}
          <DataTable table={table} />
          <DeleteConfirmationModal
            isOpen={isOpen}
            onClose={onClose}
            type={meta.label}
            id={target}
            from={group}
            handleDelete={handleDelete}
            isLoading={isDeleting}
          />
        </>
      )}
    </Deferred>
  );
};
