/*
 * Copyright 2026 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

import { createApi } from '@reduxjs/toolkit/query/react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';
import { baseQueryWithReauth } from 'dogma/features/api/baseQuery';
import { createLoginUrl } from 'dogma/util/auth';
import {
  GroupDto,
  XdsResourceDto,
  XdsResourceType,
  XDS_PROJECT,
  XDS_RESOURCE_META,
} from 'dogma/features/xds/XdsTypes';
import {
  AddRepositoryRoleDto,
  DeleteRepositoryRoleDto,
  ProjectMetadataDto,
} from 'dogma/features/xds/MetadataDto';
import { AppIdentityDto } from 'dogma/features/appidentity/AppIdentityDto';
import { CredentialDto, credentialId, XdsCredentialDto } from 'dogma/features/xds/CredentialDto';

// The repositories created automatically for every Central Dogma project. They
// are not xDS groups and must be hidden from the group list.
const INTERNAL_REPOS = new Set(['dogma', 'meta']);

interface RawRepoDto {
  name: string;
}

interface RawFileDto {
  path: string;
  type: 'TEXT' | 'DIRECTORY' | 'JSON' | 'YML';
  revision: number;
}

export interface FileContentDto {
  path: string;
  type: string;
  revision: string;
  // For JSON files the server returns the parsed object.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  content?: any;
}

export type ResourceArg = { group: string; type: XdsResourceType };
// `k8s` marks an endpoint generated by a k8s aggregator (stored under '/k8s/endpoints/'); it is read-only.
export type ResourceIdArg = ResourceArg & { id: string; k8s?: boolean };
export type CreateResourceArg = ResourceArg & { id: string; body: string };
export type UpdateResourceArg = ResourceIdArg & { body: string };

// Derives a Kubernetes endpoint aggregator id from its repository file path, e.g.
// '/k8s/endpointAggregators/foo.json' becomes 'foo'.
function k8sAggregatorIdFromPath(path: string): string {
  let id = path;
  const prefix = '/k8s/endpointAggregators/';
  if (id.startsWith(prefix)) {
    id = id.substring(prefix.length);
  }
  if (id.endsWith('.json')) {
    id = id.substring(0, id.length - '.json'.length);
  }
  return id;
}

// Derives a resource id from a repository file path, e.g.
// '/clusters/foo/bar.json' with type 'clusters' becomes 'foo/bar'.
function idFromPath(path: string, type: XdsResourceType): string {
  let id = path;
  if (id.startsWith('/')) {
    id = id.substring(1);
  }
  const prefix = `${type}/`;
  if (id.startsWith(prefix)) {
    id = id.substring(prefix.length);
  }
  if (id.endsWith('.json')) {
    id = id.substring(0, id.length - '.json'.length);
  }
  return id;
}

// Encodes a resource id for use as a URL path segment. A resource id can be nested (e.g. 'foo/bar'), and the
// server routes match it with a '**' wildcard, so the '/' separators must stay literal while each segment is
// percent-encoded.
function encodeResourcePath(id: string): string {
  return id.split('/').map(encodeURIComponent).join('/');
}

export const xdsApiSlice = createApi({
  reducerPath: 'xdsApi',
  // The login page is in the main web app at the server root (outside the '/xds' basePath), so navigate out
  // of the SPA rather than using the Next.js router.
  baseQuery: baseQueryWithReauth(() => {
    window.location.assign(createLoginUrl());
  }),
  tagTypes: ['Group', 'Resource', 'Metadata', 'AppIdentity', 'K8sAggregator', 'Credential'],
  endpoints: (builder) => ({
    // --- Groups ---
    getGroups: builder.query<GroupDto[], void>({
      query: () => `/api/v1/projects/${XDS_PROJECT}/repos`,
      transformResponse: (response: RawRepoDto[]) =>
        (response || []).filter((repo) => !INTERNAL_REPOS.has(repo.name)).map((repo) => ({ id: repo.name })),
      providesTags: ['Group'],
    }),
    addGroup: builder.mutation<unknown, { groupId: string }>({
      query: ({ groupId }) => ({
        url: `/api/v1/xds/groups?group_id=${encodeURIComponent(groupId)}`,
        method: 'POST',
        body: { name: `groups/${groupId}` },
      }),
      invalidatesTags: ['Group'],
    }),
    deleteGroup: builder.mutation<unknown, { groupId: string }>({
      query: ({ groupId }) => ({
        url: `/api/v1/xds/groups/${groupId}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Group'],
    }),

    // --- Resources (LDS/RDS/CDS/EDS) ---
    listResources: builder.query<XdsResourceDto[], ResourceArg>({
      async queryFn(arg, _queryApi, _extraOptions, fetchWithBQ) {
        const { group, type } = arg;
        // Endpoints (EDS) are not access-controlled, so they are listed through a dedicated ungated API
        // instead of the generic content API which requires the READ repository role.
        const url =
          type === 'endpoints'
            ? `/api/v1/xds/groups/${group}/endpoints`
            : `/api/v1/projects/${XDS_PROJECT}/repos/${group}/list/${type}/**?revision=head`;
        const result = await fetchWithBQ(url);
        if (result.error) {
          // The type directory does not exist until the first resource is created.
          if (result.error.status === 404) {
            return { data: [] };
          }
          return { error: result.error as FetchBaseQueryError };
        }
        const files = (result.data || []) as RawFileDto[];
        const data = files
          .filter((file) => file.type !== 'DIRECTORY')
          .map((file) => ({
            // Endpoints generated by a k8s aggregator live under '/k8s/endpoints/'; strip that prefix for a
            // clean id. They are flagged read-only by their path in the UI.
            id:
              type === 'endpoints' && file.path.startsWith('/k8s/endpoints/')
                ? file.path.slice('/k8s/endpoints/'.length).replace(/\.json$/, '')
                : idFromPath(file.path, type),
            path: file.path,
            revision: file.revision,
          }));
        return { data };
      },
      providesTags: ['Resource'],
    }),
    getResource: builder.query<FileContentDto, ResourceIdArg>({
      // Endpoints (EDS) are not access-controlled, so they are read through a dedicated ungated API instead
      // of the generic content API which requires the READ repository role. k8s-aggregator-generated endpoints
      // live under '/k8s/endpoints/' and are read via their own path.
      query: ({ group, type, id, k8s }) =>
        type === 'endpoints'
          ? k8s
            ? `/api/v1/xds/groups/${group}/k8s/endpoints/${id}`
            : `/api/v1/xds/groups/${group}/endpoints/${id}`
          : `/api/v1/projects/${XDS_PROJECT}/repos/${group}/contents/${type}/${id}.json?revision=head`,
      providesTags: ['Resource'],
    }),
    createResource: builder.mutation<unknown, CreateResourceArg>({
      query: ({ group, type, id, body }) => ({
        url: `/api/v1/xds/groups/${group}/${type}?${XDS_RESOURCE_META[type].idParam}=${encodeURIComponent(id)}`,
        method: 'POST',
        body: JSON.parse(body),
      }),
      invalidatesTags: ['Resource'],
    }),
    updateResource: builder.mutation<unknown, UpdateResourceArg>({
      query: ({ group, type, id, body }) => ({
        url: `/api/v1/xds/groups/${group}/${type}/${encodeResourcePath(id)}`,
        method: 'PATCH',
        body: JSON.parse(body),
      }),
      invalidatesTags: ['Resource'],
    }),
    deleteResource: builder.mutation<unknown, ResourceIdArg>({
      query: ({ group, type, id }) => ({
        url: `/api/v1/xds/groups/${group}/${type}/${encodeResourcePath(id)}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Resource'],
    }),

    // --- Kubernetes endpoint aggregators ---
    // Aggregators are stored under '/k8s/endpointAggregators/' in the group repository and are listed through
    // the generic (READ-gated) content API, like the other resource types.
    listK8sAggregators: builder.query<XdsResourceDto[], { group: string }>({
      async queryFn({ group }, _queryApi, _extraOptions, fetchWithBQ) {
        const result = await fetchWithBQ(
          `/api/v1/projects/${XDS_PROJECT}/repos/${group}/list/k8s/endpointAggregators/**?revision=head`,
        );
        if (result.error) {
          // The directory does not exist until the first aggregator is created.
          if (result.error.status === 404) {
            return { data: [] };
          }
          return { error: result.error as FetchBaseQueryError };
        }
        const files = (result.data || []) as RawFileDto[];
        const data = files
          .filter((file) => file.type !== 'DIRECTORY')
          .map((file) => ({
            id: k8sAggregatorIdFromPath(file.path),
            path: file.path,
            revision: file.revision,
          }));
        return { data };
      },
      providesTags: ['K8sAggregator'],
    }),
    getK8sAggregator: builder.query<FileContentDto, { group: string; id: string }>({
      query: ({ group, id }) =>
        `/api/v1/projects/${XDS_PROJECT}/repos/${group}/contents/k8s/endpointAggregators/${id}.json?revision=head`,
      providesTags: ['K8sAggregator'],
    }),
    createK8sAggregator: builder.mutation<unknown, { group: string; aggregatorId: string; body: string }>({
      query: ({ group, aggregatorId, body }) => ({
        url: `/api/v1/xds/groups/${group}/k8s/endpointAggregators?aggregator_id=${encodeURIComponent(
          aggregatorId,
        )}`,
        method: 'POST',
        body: JSON.parse(body),
      }),
      invalidatesTags: ['K8sAggregator'],
    }),
    updateK8sAggregator: builder.mutation<unknown, { group: string; id: string; body: string }>({
      // The update RPC identifies the target by the `name` field carried in the body (not the path).
      query: ({ group, id, body }) => ({
        url: `/api/v1/xds/groups/${group}/k8s/endpointAggregators/${id}`,
        method: 'PATCH',
        body: JSON.parse(body),
      }),
      invalidatesTags: ['K8sAggregator'],
    }),
    deleteK8sAggregator: builder.mutation<unknown, { group: string; id: string }>({
      query: ({ group, id }) => ({
        url: `/api/v1/xds/groups/${group}/k8s/endpointAggregators/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['K8sAggregator'],
    }),

    // --- Credentials (repository-level, under the '@xds' project) ---
    // The xDS k8s aggregator resolves a kubeconfig credential from the group's repository credentials.
    // All credential management APIs require the ADMIN repository role on the group.
    listCredentials: builder.query<XdsCredentialDto[], { group: string }>({
      query: ({ group }) => `/api/v1/projects/${XDS_PROJECT}/repos/${group}/credentials`,
      transformResponse: (response: CredentialDto[]) =>
        (response || []).map((c) => ({ id: credentialId(c.name), type: c.type })),
      providesTags: ['Credential'],
    }),
    addCredential: builder.mutation<unknown, { group: string; credentialId: string; accessToken: string }>({
      query: ({ group, credentialId: id, accessToken }) => ({
        url: `/api/v1/projects/${XDS_PROJECT}/repos/${group}/credentials`,
        method: 'POST',
        body: { credentialId: id, credential: { type: 'ACCESS_TOKEN', name: '', accessToken } },
      }),
      invalidatesTags: ['Credential'],
    }),
    deleteCredential: builder.mutation<unknown, { group: string; id: string }>({
      query: ({ group, id }) => ({
        url: `/api/v1/projects/${XDS_PROJECT}/repos/${group}/credentials/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Credential'],
    }),

    // --- Permissions (metadata) ---
    getMetadata: builder.query<ProjectMetadataDto, void>({
      query: () => `/api/v1/projects/${XDS_PROJECT}`,
      providesTags: ['Metadata'],
    }),
    addUserRepositoryRole: builder.mutation<unknown, AddRepositoryRoleDto>({
      query: ({ group, data }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/users`,
        method: 'POST',
        body: data,
      }),
      invalidatesTags: ['Metadata'],
    }),
    deleteUserRepositoryRole: builder.mutation<unknown, DeleteRepositoryRoleDto>({
      query: ({ group, id }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/users/${encodeURIComponent(id)}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Metadata'],
    }),
    addAppIdentityRepositoryRole: builder.mutation<unknown, AddRepositoryRoleDto>({
      query: ({ group, data }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/appIdentities`,
        method: 'POST',
        body: data,
      }),
      invalidatesTags: ['Metadata'],
    }),
    deleteAppIdentityRepositoryRole: builder.mutation<unknown, DeleteRepositoryRoleDto>({
      query: ({ group, id }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/appIdentities/${encodeURIComponent(id)}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Metadata'],
    }),

    // Read-only list of application identities, used to grant repository roles in the Permissions tab.
    getAppIdentities: builder.query<AppIdentityDto[], void>({
      query: () => '/api/v1/appIdentities',
      providesTags: ['AppIdentity'],
    }),
  }),
});

export const {
  useGetGroupsQuery,
  useAddGroupMutation,
  useDeleteGroupMutation,
  useListResourcesQuery,
  useGetResourceQuery,
  useCreateResourceMutation,
  useUpdateResourceMutation,
  useDeleteResourceMutation,
  useListK8sAggregatorsQuery,
  useGetK8sAggregatorQuery,
  useCreateK8sAggregatorMutation,
  useUpdateK8sAggregatorMutation,
  useDeleteK8sAggregatorMutation,
  useListCredentialsQuery,
  useAddCredentialMutation,
  useDeleteCredentialMutation,
  useGetMetadataQuery,
  useAddUserRepositoryRoleMutation,
  useDeleteUserRepositoryRoleMutation,
  useAddAppIdentityRepositoryRoleMutation,
  useDeleteAppIdentityRepositoryRoleMutation,
  useGetAppIdentitiesQuery,
} = xdsApiSlice;
