/*
 * Copyright 2026 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

import { createApi } from '@reduxjs/toolkit/query/react';
import { FetchBaseQueryError } from '@reduxjs/toolkit/query';
import { baseQueryWithReauth } from 'dogma/features/api/baseQuery';
import { createLoginUrl } from 'dogma/util/auth';
import {
  GroupDto,
  resourceName,
  XdsResourceDto,
  XdsResourceType,
  XDS_PROJECT,
  XDS_RESOURCE_META,
} from 'dogma/features/xds/XdsTypes';
import {
  extractReferences,
  resolveReference,
  XdsGraphEdge,
  XdsGraphNode,
  XdsReferenceGraph,
  XdsRefStatus,
} from 'dogma/features/xds/xdsReferences';
import {
  AddRepositoryRoleDto,
  DeleteRepositoryRoleDto,
  ProjectMetadataDto,
} from 'dogma/features/xds/MetadataDto';
import { AppIdentityDto } from 'dogma/features/appidentity/AppIdentityDto';
import { CredentialDto, credentialId, XdsCredentialDto } from 'dogma/features/xds/CredentialDto';
import { HistoryDto } from 'dogma/features/history/HistoryDto';

// The repositories created automatically for every Central Dogma project. They
// are not xDS groups and must be hidden from the group list.
const INTERNAL_REPOS = new Set(['dogma', 'meta']);

interface RawRepoDto {
  name: string;
}

interface RawFileDto {
  path: string;
  type: 'TEXT' | 'DIRECTORY' | 'JSON' | 'YML';
  revision: number;
}

export interface FileContentDto {
  path: string;
  type: string;
  revision: string;
  // For JSON files the server returns the parsed object.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  content?: any;
}

export type ResourceArg = { group: string; type: XdsResourceType };
// `k8s` marks an endpoint generated by a k8s aggregator (stored under '/k8s/endpoints/'); it is read-only.
export type ResourceIdArg = ResourceArg & { id: string; k8s?: boolean };
export type CreateResourceArg = ResourceArg & { id: string; body: string; summary?: string };
export type UpdateResourceArg = ResourceIdArg & { body: string; summary?: string };
export type DeleteResourceArg = ResourceIdArg & { summary?: string };

// Derives a Kubernetes endpoint aggregator id from its repository file path, e.g.
// '/k8s/endpointAggregators/foo.json' becomes 'foo'.
function k8sAggregatorIdFromPath(path: string): string {
  let id = path;
  const prefix = '/k8s/endpointAggregators/';
  if (id.startsWith(prefix)) {
    id = id.substring(prefix.length);
  }
  if (id.endsWith('.json')) {
    id = id.substring(0, id.length - '.json'.length);
  }
  return id;
}

// Derives a resource id from a repository file path, e.g.
// '/clusters/foo/bar.json' with type 'clusters' becomes 'foo/bar'.
function idFromPath(path: string, type: XdsResourceType): string {
  let id = path;
  if (id.startsWith('/')) {
    id = id.substring(1);
  }
  const prefix = `${type}/`;
  if (id.startsWith(prefix)) {
    id = id.substring(prefix.length);
  }
  if (id.endsWith('.json')) {
    id = id.substring(0, id.length - '.json'.length);
  }
  return id;
}

// Encodes a resource id for use as a URL path segment. A resource id can be nested (e.g. 'foo/bar'), and the
// server routes match it with a '**' wildcard, so the '/' separators must stay literal while each segment is
// percent-encoded.
function encodeResourcePath(id: string): string {
  return id.split('/').map(encodeURIComponent).join('/');
}

export const xdsApiSlice = createApi({
  reducerPath: 'xdsApi',
  // The login page is in the main web app at the server root (outside the '/xds' basePath), so navigate out
  // of the SPA rather than using the Next.js router.
  baseQuery: baseQueryWithReauth(() => {
    window.location.assign(createLoginUrl());
  }),
  tagTypes: ['Group', 'Resource', 'Metadata', 'AppIdentity', 'K8sAggregator', 'Credential'],
  endpoints: (builder) => ({
    // --- Groups ---
    getGroups: builder.query<GroupDto[], void>({
      query: () => `/api/v1/projects/${XDS_PROJECT}/repos`,
      transformResponse: (response: RawRepoDto[]) =>
        (response || []).filter((repo) => !INTERNAL_REPOS.has(repo.name)).map((repo) => ({ id: repo.name })),
      providesTags: ['Group'],
    }),
    addGroup: builder.mutation<unknown, { groupId: string }>({
      query: ({ groupId }) => ({
        url: `/api/v1/xds/groups?group_id=${encodeURIComponent(groupId)}`,
        method: 'POST',
        body: { name: `groups/${groupId}` },
      }),
      invalidatesTags: ['Group'],
    }),
    deleteGroup: builder.mutation<unknown, { groupId: string }>({
      query: ({ groupId }) => ({
        url: `/api/v1/xds/groups/${groupId}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Group'],
    }),

    // --- Resources (LDS/RDS/CDS/EDS) ---
    listResources: builder.query<XdsResourceDto[], ResourceArg>({
      async queryFn(arg, _queryApi, _extraOptions, fetchWithBQ) {
        const { group, type } = arg;
        // Endpoints (EDS) are not access-controlled, so they are listed through a dedicated ungated API
        // instead of the generic content API which requires the READ repository role.
        const url =
          type === 'endpoints'
            ? `/api/v1/xds/groups/${group}/endpoints`
            : `/api/v1/projects/${XDS_PROJECT}/repos/${group}/list/${type}/**?revision=head`;
        const result = await fetchWithBQ(url);
        if (result.error) {
          // The type directory does not exist until the first resource is created.
          if (result.error.status === 404) {
            return { data: [] };
          }
          return { error: result.error as FetchBaseQueryError };
        }
        const files = (result.data || []) as RawFileDto[];
        const data = files
          .filter((file) => file.type !== 'DIRECTORY')
          .map((file) => ({
            // Endpoints generated by a k8s aggregator live under '/k8s/endpoints/'; strip that prefix for a
            // clean id. They are flagged read-only by their path in the UI.
            id:
              type === 'endpoints' && file.path.startsWith('/k8s/endpoints/')
                ? file.path.slice('/k8s/endpoints/'.length).replace(/\.json$/, '')
                : idFromPath(file.path, type),
            path: file.path,
            revision: file.revision,
          }));
        return { data };
      },
      providesTags: ['Resource'],
    }),
    getResource: builder.query<FileContentDto, ResourceIdArg>({
      // Endpoints (EDS) are not access-controlled, so they are read through a dedicated ungated API instead
      // of the generic content API which requires the READ repository role. k8s-aggregator-generated endpoints
      // live under '/k8s/endpoints/' and are read via their own path.
      query: ({ group, type, id, k8s }) =>
        type === 'endpoints'
          ? k8s
            ? `/api/v1/xds/groups/${group}/k8s/endpoints/${id}`
            : `/api/v1/xds/groups/${group}/endpoints/${id}`
          : `/api/v1/projects/${XDS_PROJECT}/repos/${group}/contents/${type}/${id}.json?revision=head`,
      providesTags: ['Resource'],
    }),
    createResource: builder.mutation<unknown, CreateResourceArg>({
      query: ({ group, type, id, body, summary }) => {
        let url = `/api/v1/xds/groups/${group}/${type}?${XDS_RESOURCE_META[type].idParam}=${encodeURIComponent(id)}`;
        if (summary) url += `&summary=${encodeURIComponent(summary)}`;
        return { url, method: 'POST', body: JSON.parse(body) };
      },
      invalidatesTags: ['Resource'],
    }),
    updateResource: builder.mutation<unknown, UpdateResourceArg>({
      query: ({ group, type, id, body, summary }) => {
        let url = `/api/v1/xds/groups/${group}/${type}/${encodeResourcePath(id)}`;
        if (summary) url += `?summary=${encodeURIComponent(summary)}`;
        return { url, method: 'PATCH', body: JSON.parse(body) };
      },
      invalidatesTags: ['Resource'],
    }),
    deleteResource: builder.mutation<unknown, DeleteResourceArg>({
      query: ({ group, type, id, summary }) => {
        let url = `/api/v1/xds/groups/${group}/${type}/${encodeResourcePath(id)}`;
        if (summary) url += `?summary=${encodeURIComponent(summary)}`;
        return { url, method: 'DELETE' };
      },
      invalidatesTags: ['Resource'],
    }),

    // --- Kubernetes endpoint aggregators ---
    // Aggregators are stored under '/k8s/endpointAggregators/' in the group repository and are listed through
    // the generic (READ-gated) content API, like the other resource types.
    listK8sAggregators: builder.query<XdsResourceDto[], { group: string }>({
      async queryFn({ group }, _queryApi, _extraOptions, fetchWithBQ) {
        const result = await fetchWithBQ(
          `/api/v1/projects/${XDS_PROJECT}/repos/${group}/list/k8s/endpointAggregators/**?revision=head`,
        );
        if (result.error) {
          // The directory does not exist until the first aggregator is created.
          if (result.error.status === 404) {
            return { data: [] };
          }
          return { error: result.error as FetchBaseQueryError };
        }
        const files = (result.data || []) as RawFileDto[];
        const data = files
          .filter((file) => file.type !== 'DIRECTORY')
          .map((file) => ({
            id: k8sAggregatorIdFromPath(file.path),
            path: file.path,
            revision: file.revision,
          }));
        return { data };
      },
      providesTags: ['K8sAggregator'],
    }),
    getK8sAggregator: builder.query<FileContentDto, { group: string; id: string }>({
      query: ({ group, id }) =>
        `/api/v1/projects/${XDS_PROJECT}/repos/${group}/contents/k8s/endpointAggregators/${id}.json?revision=head`,
      providesTags: ['K8sAggregator'],
    }),
    // Dry-run preview: resolves the aggregator's watchers against Kubernetes and returns the
    // ClusterLoadAssignment that would be generated, without persisting.
    previewK8sAggregator: builder.mutation<
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      any, // ClusterLoadAssignment JSON
      { group: string; body: string }
    >({
      query: ({ group, body }) => ({
        url: `/api/v1/xds/groups/${group}/k8s/endpointAggregators/preview`,
        method: 'POST',
        body: JSON.parse(body),
      }),
    }),
    createK8sAggregator: builder.mutation<
      unknown,
      { group: string; aggregatorId: string; body: string; summary?: string }
    >({
      query: ({ group, aggregatorId, body, summary }) => {
        let url = `/api/v1/xds/groups/${group}/k8s/endpointAggregators?aggregator_id=${encodeURIComponent(aggregatorId)}`;
        if (summary) url += `&summary=${encodeURIComponent(summary)}`;
        return { url, method: 'POST', body: JSON.parse(body) };
      },
      invalidatesTags: ['K8sAggregator'],
    }),
    updateK8sAggregator: builder.mutation<
      unknown,
      { group: string; id: string; body: string; summary?: string }
    >({
      // The update RPC identifies the target by the `name` field carried in the body (not the path).
      query: ({ group, id, body, summary }) => {
        let url = `/api/v1/xds/groups/${group}/k8s/endpointAggregators/${id}`;
        if (summary) url += `?summary=${encodeURIComponent(summary)}`;
        return { url, method: 'PATCH', body: JSON.parse(body) };
      },
      invalidatesTags: ['K8sAggregator'],
    }),
    deleteK8sAggregator: builder.mutation<unknown, { group: string; id: string; summary?: string }>({
      query: ({ group, id, summary }) => {
        let url = `/api/v1/xds/groups/${group}/k8s/endpointAggregators/${id}`;
        if (summary) url += `?summary=${encodeURIComponent(summary)}`;
        return { url, method: 'DELETE' };
      },
      invalidatesTags: ['K8sAggregator'],
    }),

    // --- Credentials (repository-level, under the '@xds' project) ---
    // The xDS k8s aggregator resolves a kubeconfig credential from the group's repository credentials.
    // All credential management APIs require the ADMIN repository role on the group.
    listCredentials: builder.query<XdsCredentialDto[], { group: string }>({
      query: ({ group }) => `/api/v1/projects/${XDS_PROJECT}/repos/${group}/credentials`,
      transformResponse: (response: CredentialDto[]) =>
        (response || []).map((c) => ({ id: credentialId(c.name), type: c.type })),
      providesTags: ['Credential'],
    }),
    addCredential: builder.mutation<unknown, { group: string; credentialId: string; accessToken: string }>({
      query: ({ group, credentialId: id, accessToken }) => ({
        url: `/api/v1/projects/${XDS_PROJECT}/repos/${group}/credentials`,
        method: 'POST',
        body: { credentialId: id, credential: { type: 'ACCESS_TOKEN', name: '', accessToken } },
      }),
      invalidatesTags: ['Credential'],
    }),
    deleteCredential: builder.mutation<unknown, { group: string; id: string }>({
      query: ({ group, id }) => ({
        url: `/api/v1/projects/${XDS_PROJECT}/repos/${group}/credentials/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Credential'],
    }),

    // --- Permissions (metadata) ---
    getMetadata: builder.query<ProjectMetadataDto, void>({
      query: () => `/api/v1/projects/${XDS_PROJECT}`,
      providesTags: ['Metadata'],
    }),
    addUserRepositoryRole: builder.mutation<unknown, AddRepositoryRoleDto>({
      query: ({ group, data }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/users`,
        method: 'POST',
        body: data,
      }),
      invalidatesTags: ['Metadata'],
    }),
    deleteUserRepositoryRole: builder.mutation<unknown, DeleteRepositoryRoleDto>({
      query: ({ group, id }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/users/${encodeURIComponent(id)}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Metadata'],
    }),
    addAppIdentityRepositoryRole: builder.mutation<unknown, AddRepositoryRoleDto>({
      query: ({ group, data }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/appIdentities`,
        method: 'POST',
        body: data,
      }),
      invalidatesTags: ['Metadata'],
    }),
    deleteAppIdentityRepositoryRole: builder.mutation<unknown, DeleteRepositoryRoleDto>({
      query: ({ group, id }) => ({
        url: `/api/v1/metadata/${XDS_PROJECT}/repos/${group}/roles/appIdentities/${encodeURIComponent(id)}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Metadata'],
    }),

    // Read-only list of application identities, used to grant repository roles in the Permissions tab.
    getAppIdentities: builder.query<AppIdentityDto[], void>({
      query: () => '/api/v1/appIdentities',
      providesTags: ['AppIdentity'],
    }),

    // --- Change history ---
    // The commit history (newest first) of a group repository, optionally scoped to a single resource file via
    // `filePath`. Each create/update/delete of an xDS resource is a commit. `to=1` makes the range span from
    // HEAD back to the first revision; without it the range would collapse to HEAD only and return nothing.
    getGroupHistory: builder.query<HistoryDto[], { group: string; filePath?: string; maxCommits?: number }>({
      query: ({ group, filePath = '/**', maxCommits = 100 }) =>
        `/api/v1/projects/${XDS_PROJECT}/repos/${group}/commits/head?path=${encodeURIComponent(filePath)}&to=1&maxCommits=${maxCommits}`,
      providesTags: ['Resource'],
    }),

    // --- Reference graph ---
    // Builds the group's resource reference graph (nodes + edges) on the client: it lists every resource, reads
    // the content of the referencing types (LDS/RDS/CDS) and extracts their references to RDS/CDS/EDS, marking
    // each edge ok / missing (dangling) / external. Powers the References (search + reverse-reference) view.
    getGroupGraph: builder.query<XdsReferenceGraph, { group: string }>({
      async queryFn({ group }, _queryApi, _extraOptions, fetchWithBQ) {
        const TYPES: XdsResourceType[] = ['listeners', 'routes', 'clusters', 'endpoints'];
        const filesByType: Record<XdsResourceType, RawFileDto[]> = {
          listeners: [],
          routes: [],
          clusters: [],
          endpoints: [],
        };
        for (const type of TYPES) {
          // Endpoints (EDS) are not access-controlled, so they are listed through the dedicated ungated API.
          const url =
            type === 'endpoints'
              ? `/api/v1/xds/groups/${group}/endpoints`
              : `/api/v1/projects/${XDS_PROJECT}/repos/${group}/list/${type}/**?revision=head`;
          const res = await fetchWithBQ(url);
          if (res.error) {
            // The type directory does not exist until the first resource is created.
            if ((res.error as FetchBaseQueryError).status === 404) {
              continue;
            }
            return { error: res.error as FetchBaseQueryError };
          }
          filesByType[type] = ((res.data || []) as RawFileDto[]).filter((file) => file.type !== 'DIRECTORY');
        }

        const idOf = (type: XdsResourceType, path: string): string =>
          type === 'endpoints' && path.startsWith('/k8s/endpoints/')
            ? path.slice('/k8s/endpoints/'.length).replace(/\.json$/, '')
            : idFromPath(path, type);

        const nodes: XdsGraphNode[] = [];
        const idsByType: Record<XdsResourceType, Set<string>> = {
          listeners: new Set(),
          routes: new Set(),
          clusters: new Set(),
          endpoints: new Set(),
        };
        for (const type of TYPES) {
          for (const file of filesByType[type]) {
            const id = idOf(type, file.path);
            nodes.push({ type, id, name: resourceName(group, file.path), k8s: file.path.startsWith('/k8s/') });
            idsByType[type].add(id);
          }
        }

        // Only listeners, routes and clusters declare outgoing references; read their content to extract them.
        // All fetches run in parallel to avoid serial RTT accumulation on large groups.
        const REF_TYPES: XdsResourceType[] = ['listeners', 'routes', 'clusters'];
        const edgeArrays = await Promise.all(
          REF_TYPES.flatMap((type) =>
            filesByType[type].map(async (file) => {
              const localEdges: XdsGraphEdge[] = [];
              const res = await fetchWithBQ(
                `/api/v1/projects/${XDS_PROJECT}/repos/${group}/contents${file.path}?revision=head`,
              );
              if (res.error) {
                // Skip resources that cannot be read; they simply contribute no edges.
                return localEdges;
              }
              const content = (res.data as FileContentDto)?.content;
              const fromId = idOf(type, file.path);
              const fromName = resourceName(group, file.path);
              for (const ref of extractReferences(type, JSON.stringify(content ?? {}))) {
                const link = resolveReference(group, ref);
                const status: XdsRefStatus =
                  link.group !== group ? 'external' : idsByType[ref.targetType].has(link.id) ? 'ok' : 'missing';
                localEdges.push({
                  fromType: type,
                  fromId,
                  fromName,
                  targetType: ref.targetType,
                  targetId: link.id,
                  targetGroup: link.group,
                  targetK8s: link.k8s,
                  name: ref.name,
                  status,
                });
              }
              return localEdges;
            }),
          ),
        );
        const edges: XdsGraphEdge[] = edgeArrays.flat();
        return { data: { nodes, edges } };
      },
      providesTags: ['Resource'],
    }),
  }),
});

export const {
  useGetGroupsQuery,
  useAddGroupMutation,
  useDeleteGroupMutation,
  useListResourcesQuery,
  useGetResourceQuery,
  useCreateResourceMutation,
  useUpdateResourceMutation,
  useDeleteResourceMutation,
  useListK8sAggregatorsQuery,
  useGetK8sAggregatorQuery,
  usePreviewK8sAggregatorMutation,
  useCreateK8sAggregatorMutation,
  useUpdateK8sAggregatorMutation,
  useDeleteK8sAggregatorMutation,
  useListCredentialsQuery,
  useAddCredentialMutation,
  useDeleteCredentialMutation,
  useGetMetadataQuery,
  useAddUserRepositoryRoleMutation,
  useDeleteUserRepositoryRoleMutation,
  useAddAppIdentityRepositoryRoleMutation,
  useDeleteAppIdentityRepositoryRoleMutation,
  useGetAppIdentitiesQuery,
  useGetGroupHistoryQuery,
  useGetGroupGraphQuery,
} = xdsApiSlice;
