// Generated by the ':site-new:versionIndex' Gradle task from gradle.properties.
// This is the Docusaurus equivalent of Sphinx's `|release|` substitution.
import versions from '../gen-src/versions.json';

export const release: string = versions.release;

export const downloadUrl = `https://github.com/line/centraldogma/releases/download/centraldogma-${release}/centraldogma-${release}.tgz`;
