/*
 * Copyright 2017 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package com.linecorp.centraldogma.server.internal.credential;

import static java.util.Objects.requireNonNull;

import javax.annotation.Nullable;

import com.google.common.base.MoreObjects;
import com.google.common.base.MoreObjects.ToStringHelper;
import com.google.common.base.Objects;

import com.linecorp.centraldogma.server.credential.Credential;
import com.linecorp.centraldogma.server.credential.CredentialType;

abstract class AbstractCredential implements Credential {

    @Nullable
    private final String name;
    private final String id;
    private final CredentialType type;

    AbstractCredential(@Nullable String name, CredentialType type) {
        // The name of the credential can be null when the client creates a new credential.
        // The name is automatically generated by the server.
        this.name = name;
        id = extractId(name, type);
        this.type = requireNonNull(type, "type");
    }

    private static String extractId(@Nullable String name, CredentialType type) {
        if (name == null) {
            return "";
        }
        if (type == CredentialType.NONE && name.isEmpty()) {
            // The name of the NONE credential can be empty.
            return "";
        }
        final int lastIndex = name.lastIndexOf('/');
        if (lastIndex < 0) {
            // Just return an empty string because the credential name isn't set properly by the server yet.
            return "";
        }
        // Credential name is validated when creating in CredentialService so just extract the id.
        return name.substring(lastIndex + 1);
    }

    @Override
    public final String id() {
        return id;
    }

    @Override
    public String name() {
        // The name is not null when this method is called because the name is automatically generated
        // by the server when the client creates a new credential.
        //noinspection DataFlowIssue
        return name;
    }

    @Override
    public final CredentialType type() {
        return type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final AbstractCredential that = (AbstractCredential) o;
        return Objects.equal(name, that.name) && type == that.type;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(name, type);
    }

    @Override
    public final String toString() {
        final ToStringHelper helper = MoreObjects.toStringHelper(this).omitNullValues();
        helper.add("name", name);
        helper.add("type", type);
        addProperties(helper);
        return helper.toString();
    }

    abstract void addProperties(ToStringHelper helper);
}
