name: CI
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  # Cancel the previous builds in the same PR.
  # Allow running concurrently for all non-PR commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      GRADLE_OPTS: -Xmx1280m
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11]
        include:
          - java: 11
            os: ubuntu-latest
            coverage: true
          - java: 8
            os: ubuntu-latest
          - java: 17
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: |
        ./gradlew --no-daemon --stacktrace -Pcoverage -PnoLint build \
        -PbuildJdkVersion=${{ matrix.java }} \
        -PtestJavaVersion=${{ matrix.java }} \
      shell: bash

    - name: Upload coverage to Codecov
      if: ${{ matrix.coverage }}
      uses: codecov/codecov-action@v1

    - name: Collecting the test reports ..
      if: failure()
      run: find . '(' -name 'hs_err_*.log' -or -path '*/build/reports/tests' ')' -exec tar rf "reports-JVM-${{ matrix.java }}.tar" {} ';'
      shell: bash

    - name: Upload Artifact
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: reports-JVM-${{ matrix.java }}
        path: reports-JVM-${{ matrix.java }}.tar
        retention-days: 3

    - name: Dump stuck threads
      if: always()
      run: jps | grep -vi "jps" | awk '{ print $1 }' | xargs -I'{}' jstack -l {} || true
      shell: bash

  lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      GRADLE_OPTS: -Xmx1280m
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace lint \
          -PbuildJdkVersion=${{ matrix.java }} \
          -PtestJavaVersion=${{ matrix.java }}
        shell: bash
